name: Generate and Save Plots

on:
  push:
    branches:
      - main

jobs:
  generate_plots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YT shorts analysis
        run: |
          python ys_shorts_trends.py

      - name: Upload plots as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-plots
          path: plots/
